### ISSUE TITLE
Any way to turn off LED lights? 

### ISSUE THREAD

**Issue by kevindesai777** [xrigau/androidthings-rgb-led#4]
Thought close method would do it. But it does not. Any other way to turn off LED lights? And turn them back on later on?

**Comment by xrigau** [comment]
The `close` method will close the connection to the LED strip so this should only be done when you don't want to use the LED strip anymore.

Sending `Color.BLACK` (000000) should turn the LEDs off, and then sending any other color should turn them back on. Let me know if you have any other issues

**Comment by kevindesai777** [comment]
Thanks for the quick response!

**Comment by xrigau** [comment]
👍 no problem :)
