### ISSUE TITLE
Bugfix not updated in jcenter? 

### ISSUE THREAD

**Issue by kevindesai777** [xrigau/androidthings-rgb-led#5]
Hi, I remember submitting a pull request for a bugfix. But it seems like the jcenter dependency has not been updated. I am still getting the crash error due to the bug. Can you look into it?

**Comment by xrigau** [comment]
you're right! I totally forgot to do it, sorry! I just pushed `0.0.2` https://bintray.com/xrigau/maven/ws2801-driver/0.0.2
